version: '3'

services:
  blocky:
    image: spx01/blocky:latest
    container_name: blocky
    restart: unless-stopped
    network_mode: "host" # or use a bridge network if needed
    volumes:
      - ./config.yml:/app/config.yml
      - ./logs:/app/logs
    environment:
      - TZ=Etc/UTC  # Change this to your timezone
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"  # Web dashboard (if enabled)
