services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - INSTANCE_NAME=DrkXo SearXNG
      - SEARXNG_BASE_URL=http://localhost:8080/
      - SEARXNG_SECRET_KEY=b94f3575bfab0c31f496e976221e89cd1b846358324b0cf127ede5e44ce70c6e
      - SEARXNG_PORT=8080
      - AUTOCOMPLETE=duckduckgo
#      - CONTACT_URL=mailto:admin@example.com
    volumes:
      - ./searxng:/etc/searxng:rw
    cap_drop: # For 1st run disable this section
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"