services:
  mobsf:
    image: opensecurity/mobile-security-framework-mobsf:latest
    container_name: mobsf

    user: root

    ports:
      - "8999:8000"

    stdin_open: true
    tty: true

    security_opt:
      - seccomp=unconfined

    restart: unless-stopped
    networks:
      - privacy-net
    volumes:
      - ./mobsf_data:/home/mobsf/.MobSF


networks:
  privacy-net:
    external: true
