User nobody
Group nobody

Port 8888

Timeout 600

# LogLevel Info
# LogFile "/var/log/tinyproxy/tinyproxy.log"

# Remove PID file completely for containers
# PidFile "/run/tinyproxy/tinyproxy.pid"

# Allow everyone
Allow 0.0.0.0/0

# Preserve original headers/cookies/auth
DisableViaHeader Yes

# HTTPS CONNECT support
ConnectPort 443
ConnectPort 80

# Better compatibility
XTinyproxy Yes
