include:
  - flaresolverr/flaresolverr.yml
  - tachidesk/tachidesk.yml
  - stremio/stremio.yml
  - adguardhome/adguardhome.yml
  # - kavita/kavita.yml
  # - calibre-web/calibre-web.yml
  # - dnscrypt/dnscrypt.yml
  # - unbound/unbound.yml
